version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    restart: always
    volumes:
      - ./zookeeper-persistance:/bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - cluster-network
  kafka:
    image: bitnami/kafka:3.3.1
    restart: always
    volumes:
      - ./kafka-persistance/node1:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://127.0.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on: 
      - zookeeper
    networks:
      - cluster-network
  kafka2:
    image: bitnami/kafka:3.3.1
    restart: always
    volumes:
       - ./kafka-persistance/node2:/bitnami/kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:29093,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:29093,EXTERNAL://127.0.0.1:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - cluster-network
  kafka3:
    image: bitnami/kafka:3.3.1
    restart: always
    volumes:
      - ./kafka-persistance/node3:/bitnami/kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:29094,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:29094,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - cluster-network
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    restart: always
    volumes:
      - ./opensearch-persistance:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      # along with the memlock settings below, disables swapping
      - bootstrap.memory_lock=true
      # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
      - "discovery.type=single-node"
      # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "DISABLE_SECURITY_PLUGIN=true"
      # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_INSTALL_DEMO_CONFIG=true" 
      # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - cluster-network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      # disables security dashboards plugin in OpenSearch Dashboards
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - cluster-network
  postgres:
    image: postgres:14.5
    volumes:
      - ./postgres-persistance:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - cluster-network
  padmin:
    image: dpage/pgadmin4:6.14
    volumes:
      - ./padmin-persistance:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    networks:
      - cluster-network

networks:
  cluster-network:
    driver: bridge